#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime environment changes to make the snap work here.  You may also insert security confinement/deprecation/obsoletion notice of the snap here.

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

# HACK: Executable depend on shared library under the same directory
# HACK: Application need to create directory under executable directory
cp \
	--force \
	--remove-destination \
	--verbose \
	"${SNAP}"/TdhCad_linux \
	"${SNAP_USER_COMMON}"

ln \
	--force \
	--symbolic \
	--verbose \
	"${SNAP}"/libTdhCairo.so \
	"${SNAP}"/*.pdf \
	"${SNAP_USER_COMMON}"
mkdir \
	--verbose \
	--parents \
	"${SNAP_USER_COMMON}"/TdhCad_Structure
ln \
	--force \
	--symbolic \
	--verbose \
	"${SNAP}"/TdhCad_Structure/TdhCad.sqlite \
	"${SNAP_USER_COMMON}"/TdhCad_Structure

cp \
	--no-clobber \
	--verbose \
	"${SNAP}"/TdhCad_Structure/TdhCad_config.sqlite \
	"${SNAP_USER_COMMON}"/TdhCad_Structure

cd "${SNAP_USER_COMMON}"
./TdhCad_linux
